# User overrides belong in ~/.config/gcr/config.sh (or GCR_CONFIG_FILE).
: "${CHECK_GCR_UPDATE:=true}"
: "${AUTO_GCR_UPDATE:=false}"
: "${SHOW_GCR_INFO:=false}"
: "${GCR_LOAD_THEME:=true}"
: "${GCR_UPDATE_INTERVAL:=86400}"
: "${GCR_CONNECT_TIMEOUT:=5}"
: "${GCR_DOWNLOAD_TIMEOUT:=30}"
: "${GCR_REPOSITORY:=gaojunbin/GCR}"
: "${GCR_UPDATE_REF:=master}"
: "${GCR_API_URL:=https://api.github.com}"
: "${GCR_RAW_URL:=https://raw.githubusercontent.com}"
: "${GCR_STATE_DIR:=$GCR_INSTALL_ROOT/.gcr/state}"
: "${GCR_SERVICE_DIR:=$GCR_INSTALL_ROOT/services}"
